/**
 * MoCo rent increase notice letter generator.
 *
 * Montgomery County requires 90 days written notice before a rent increase
 * takes effect (Chapter 29, Article II).
 *
 * This returns plain text — the UI lets the landlord edit before download.
 */

export interface NoticeParams {
  landlordName: string;
  propertyAddress: string;
  unitId: string;
  tenantName: string | null;
  currentRent: number;
  proposedRent: number;
  /** ISO date string 'YYYY-MM-DD' */
  effectiveDate: string;
  /** Today's date (the notice date), ISO string */
  noticeDate: string;
}

/** Format a dollar amount: "$1,950.00" */
function fmt(n: number): string {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 });
}

/** Format ISO date → "Month D, YYYY" */
function fmtDate(iso: string): string {
  const [y, m, d] = iso.split('-').map(Number);
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];
  return `${months[m - 1]} ${d}, ${y}`;
}

export function generateNotice(params: NoticeParams): string {
  const {
    landlordName,
    propertyAddress,
    unitId,
    tenantName,
    currentRent,
    proposedRent,
    effectiveDate,
    noticeDate,
  } = params;

  const increase = proposedRent - currentRent;
  const increasePct = ((increase / currentRent) * 100).toFixed(2);
  const salutation = tenantName ? `Dear ${tenantName},` : 'Dear Resident,';
  const addressee = tenantName ?? 'Resident';

  return `
${fmtDate(noticeDate)}

${addressee}
Unit ${unitId}
${propertyAddress}

${salutation}

NOTICE OF RENT INCREASE — MONTGOMERY COUNTY RENT STABILIZATION

This notice is provided pursuant to Montgomery County Code, Chapter 29,
Article II (Rent Stabilization). You are hereby notified that your rent will
increase effective ${fmtDate(effectiveDate)}, which is at least ninety (90)
days from the date of this notice.

  Current monthly rent:   ${fmt(currentRent)}
  New monthly rent:       ${fmt(proposedRent)}
  Monthly increase:       ${fmt(increase)} (${increasePct}%)
  Effective date:         ${fmtDate(effectiveDate)}

This increase complies with the Montgomery County Rent Stabilization Program.
You may contact the Montgomery County Department of Housing and Community
Affairs (DHCA) at (240) 777-3600 or rentstabilization@montgomerycountymd.gov
with any questions about your rights under the rent stabilization law.

If you have questions about this notice, please contact us at the address
or phone number below.

Sincerely,

${landlordName}
${propertyAddress}


---
This notice was generated by the MoCo Rent Optimizer on ${fmtDate(noticeDate)}.
`.trim();
}
